// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-0nSqJgzMshhGAZTn4aQHxb06gSsxpY0',
    appId: '1:729888988317:web:b860777892c8d12b1ec874',
    messagingSenderId: '729888988317',
    projectId: 'capstoneproject-sf2025',
    authDomain: 'capstoneproject-sf2025.firebaseapp.com',
    storageBucket: 'capstoneproject-sf2025.firebasestorage.app',
    measurementId: 'G-BYDWNF40GX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcpBYqLX-HZwGlC7_9fq6F8XQUrKHG9Yo',
    appId: '1:729888988317:android:790822a347d4c0e61ec874',
    messagingSenderId: '729888988317',
    projectId: 'capstoneproject-sf2025',
    storageBucket: 'capstoneproject-sf2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKYWSyPK2w55K00JoJ62PUtHUEgtnccz0',
    appId: '1:729888988317:ios:bad8f3063572a23c1ec874',
    messagingSenderId: '729888988317',
    projectId: 'capstoneproject-sf2025',
    storageBucket: 'capstoneproject-sf2025.firebasestorage.app',
    iosBundleId: 'com.example.capstone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKYWSyPK2w55K00JoJ62PUtHUEgtnccz0',
    appId: '1:729888988317:ios:bad8f3063572a23c1ec874',
    messagingSenderId: '729888988317',
    projectId: 'capstoneproject-sf2025',
    storageBucket: 'capstoneproject-sf2025.firebasestorage.app',
    iosBundleId: 'com.example.capstone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-0nSqJgzMshhGAZTn4aQHxb06gSsxpY0',
    appId: '1:729888988317:web:993c15aaf306b2281ec874',
    messagingSenderId: '729888988317',
    projectId: 'capstoneproject-sf2025',
    authDomain: 'capstoneproject-sf2025.firebaseapp.com',
    storageBucket: 'capstoneproject-sf2025.firebasestorage.app',
    measurementId: 'G-BPFFCYM1PN',
  );
}
